Fix for Uncaught TypeError: strlen() expects parameter 1 to be string
Fatal error: Uncaught TypeError: strlen() expects parameter 1 to be string, null given in vendor/myparcelnl/sdk/src/Model/Consignment/AbstractConsignment.php:703